<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RewriteSocialBatchFiveSeeder extends Seeder
{
 public function run(){
  $items=[
   ['instagram-photo-downloader-full-size-image-guide','Instagram Photos: Check Full-Size Quality','Instagram photos','A full-size image should preserve the original crop, text, and color. Check the individual public post and creator context before keeping a permitted copy.'],
   ['instagram-to-mp4-reels-and-video-format-guide','Instagram to MP4: Keep Reels Compatible','Instagram MP4','MP4 is a container, so check sound, portrait orientation, duration, and phone playback instead of trusting the extension alone.'],
   ['download-full-size-instagram-photos-safe-guide','Instagram Images: Safe Resolution and Storage Tips','Instagram image storage','Choose a size that remains sharp on the target screen without filling storage unnecessarily. Keep the source URL and creator credit.'],
   ['descargar-video-instagram-guia-segura-en-mp4','Instagram Video MP4: A Clear English Guide','Instagram video MP4','Start with the individual public post, confirm permission, then check the saved MP4 for audio, duration, and portrait framing.'],
   ['descargar-stories-instagram-guia-de-uso-responsable','Instagram Stories: Save Your Own Archive Responsibly','Instagram Stories','Stories disappear quickly, so your own original camera file is the best archive. Keep other creators’ stories only with clear permission.'],
   ['pinterest-downloader-video-and-image-saving-guide','Pinterest Pins: Separate Video and Image Workflows','Pinterest Pins','A video Pin and a still image need different checks. Follow the source link, preserve the crop, and keep creator context with any permitted file.'],
   ['download-pinterest-videos-mp4-quality-guide','Pinterest Video MP4: Test Before Sharing','Pinterest MP4','Play the beginning, middle, and end of an authorized Pin copy and check captions, audio, and aspect ratio before sharing.'],
   ['pinterest-video-saver-organize-saved-pins','Pinterest Video Files: Organize a Small Archive','Pinterest archive','Use descriptive filenames, source URLs, dates, and creator names so saved Pins remain useful and attributable later.'],
   ['dailymotion-video-downloader-public-video-guide','Dailymotion Public Videos: Check the Source First','Dailymotion public videos','Open the individual public video, verify availability, and test the resulting file on the device where you plan to use it.'],
   ['dailymotion-downloader-mp4-saving-guide','Dailymotion MP4: Fix Common Playback Problems','Dailymotion MP4','Check for missing audio, incomplete duration, unsupported codecs, or a wrong filename before trying another conversion.'],
  ];
  $slugs=array_column($items,0);$rows=DB::table('blog_posts')->whereIn('slug',$slugs)->lockForUpdate()->get();if($rows->count()!==10)throw new \RuntimeException('Target articles missing; stopped safely.');
  DB::transaction(function()use($items,$rows){$backup=dirname(base_path()).'/social-batch-five-'.date('Ymd-His').'.json';file_put_contents($backup,json_encode($rows,JSON_PRETTY_PRINT),LOCK_EX);chmod($backup,0600);foreach($items as [$slug,$title,$focus,$intro]){$platform=str_contains($slug,'dailymotion')?'dailymotion':(str_contains($slug,'pinterest')?'pinterest':'instagram');$content='<p>'.$intro.' This guide focuses on one clear task so you can check the result instead of guessing from a filename.</p><h2>Start with the individual source</h2><p>Open the exact post, Pin, Story, or video and confirm it is available publicly. Keep only your own work, licensed material, public-domain content, or a copy the creator has permitted. A public player does not automatically grant reuse rights.</p><h2>Check the finished file</h2><ol><li>Play the opening and final seconds.</li><li>Check sound and synchronization.</li><li>Inspect captions or fine detail.</li><li>Confirm the orientation and duration.</li></ol><p>If the file is not visible, look in the browser Downloads folder as well as Photos or Gallery. If it is blurry only after sharing, the destination app compressed it.</p><h2>Keep the source context</h2><p>Use a descriptive filename and store the source URL, creator name, and date beside it. Do not share passwords, cookies, or install an unknown application to process a public link.</p><p>Use the <a href="/'.$platform.'-video-downloader">'.$platform.' platform guide</a> for source checks and the <a href="/supported-platforms">supported platforms directory</a> for other services.</p>';$data=['title'=>$title,'excerpt'=>$focus,'meta_title'=>$title,'meta_description'=>$focus,'content'=>$content,'read_minutes'=>1,'updated_at'=>now()];DB::table('blog_posts')->where('slug',$slug)->update($data);}$this->command->info('Updated 10 articles. Backup: '.$backup);});
 }
}
