<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RewriteSocialBatchFourSeeder extends Seeder
{
 public function run(){
  $items=[
   ['facebook-video-downloader-complete-public-video-guide','Facebook Public Videos: A Link and Permission Checklist','public Facebook videos','Confirm the individual post is public, copy its link, and keep creator credit with any permitted copy. A public player does not grant permission to republish.','Open the post; verify the creator; test picture, sound, and duration; save the source URL.'],
   ['download-facebook-video-quality-and-safety-guide','Facebook Video Quality: Keep Text and Audio Clear','Facebook video quality','Quality is judged on the actual phone or laptop, not by a filename. Compare text, speech, and motion before choosing a smaller copy.','Check a text frame; listen for sync; play the ending; keep the original before resizing.'],
   ['video-download-for-facebook-app-what-works-safely','Facebook App Videos: Safer Ways to Keep Your Own Clips','Facebook app videos','For your own clips, check the camera roll, editing project, and account export before using any third-party link tool. Never share passwords or cookies.','Find the original; compare versions; keep permission notes; test the backup after transfer.'],
   ['how-to-save-facebook-videos','How to Organize Saved Facebook Videos','saved Facebook videos','A useful archive needs creator, date, source link, and intended use beside the file. This prevents a saved clip becoming an unattributed mystery.','Use descriptive names; group by project; store the source URL; review old files before reuse.'],
   ['facebook-video-downloader-chrome-browser-safety-guide','Facebook Links in Chrome: Troubleshoot the Browser First','Facebook links in Chrome','When a public link fails, check the individual post, browser download history, storage, and whether the file actually arrived.','Recopy the post link; try a private window; check Downloads; open the result on the target device.'],
   ['facebook-video-downloader-4k-resolution-guide','Facebook 4K Claims: What the Source Really Provides','Facebook 4K video','A 4K label cannot create detail missing from a source. Inspect dimensions and a fine-detail frame before keeping a larger file.','Compare source and copy; inspect text; check codec support; avoid repeated re-encoding.'],
   ['facebook-reel-video-downloader-reels-format-guide','Facebook Reels: Preserve Portrait Framing','Facebook Reels format','Reels are commonly portrait. Keep the original frame so captions, faces, and product details are not cropped by a landscape preset.','Check top and bottom edges; test rotation; watch the complete clip; keep creator credit.'],
   ['facebook-video-downloader-apk-safety-before-installing','Facebook Video APKs: What to Check Before Installing Anything','Facebook APK safety','A video link should not require an unknown APK or a Facebook password. Use browser and official account routes, and scan files before opening them.','Avoid sideloaded tools; review permissions; do not share cookies; remove suspicious downloads.'],
   ['how-to-download-a-saved-video-from-facebook','Find a Facebook Video You Already Saved','saved Facebook post','A saved post inside Facebook is a bookmark, not necessarily a local file. Reopen the post, check its availability, and use the creator-approved route for a copy.','Open Saved; revisit the original post; check privacy; record the source before filing a local copy.'],
   ['twitter-video-downloader-save-x-videos-in-mp4','X Videos in MP4: Check the Source and the File','X video MP4','For an authorized X video copy, confirm the post, creator, duration, and audio before sharing. Keep the post URL because embedded media can change.','Verify the post; inspect portrait or landscape shape; play the ending; preserve attribution.'],
  ];
  $rows=DB::table('blog_posts')->whereIn('slug',array_column($items,0))->lockForUpdate()->get();if($rows->count()!==10)throw new \RuntimeException('Target articles missing; stopped safely.');
  DB::transaction(function()use($items,$rows){$backup=dirname(base_path()).'/social-batch-four-'.date('Ymd-His').'.json';file_put_contents($backup,json_encode($rows,JSON_PRETTY_PRINT),LOCK_EX);chmod($backup,0600);foreach($items as [$slug,$title,$excerpt,$focus,$steps]){$content='<p>'.$focus.' The goal is a useful copy with clear context, not a vague promise about every link working everywhere.</p><h2>Start with the source</h2><p>'.$steps.' Open the individual post and make sure it is available without bypassing a private account, login wall, or other access control.</p><h2>Check the finished file</h2><p>Play the beginning, a middle section, and the final seconds. Check audio sync, orientation, captions, and duration on the device where you will use it. If a file is missing from the gallery, look in the browser Downloads folder as well.</p><h2>Keep rights and safety clear</h2><p>Save your own work, licensed media, public-domain material, or a file the creator has permitted. Do not give a downloader your password, cookies, or permission to install an unknown application. Keep the source URL and creator name next to the file.</p><h2>Use the relevant guide</h2><p>Check the <a href="/facebook-video-downloader">Facebook platform guide</a> for Facebook sources, or the <a href="/twitter-video-downloader">Twitter/X platform guide</a> for X posts. The <a href="/supported-platforms">supported platforms directory</a> lists other public sources.</p>';$data=['title'=>$title,'excerpt'=>$excerpt,'meta_title'=>$title,'meta_description'=>$excerpt,'content'=>$content,'read_minutes'=>1,'updated_at'=>now()];DB::table('blog_posts')->where('slug',$slug)->update($data);} $this->command->info('Updated 10 articles. Backup: '.$backup);});
 }
}
