<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RewriteTikTokBatchTenSeeder extends Seeder
{
 public function run(){
  $items=[
   ['tiktok-video-downloader-hd-public-video-guide','TikTok HD: Check Detail Before Keeping a Copy','TikTok HD detail'],['download-tiktok-video-no-app-guide','TikTok in a Browser: Keep the Workflow Simple','browser workflow without an unknown app'],['download-tiktok-videos-quality-and-permission-guide','TikTok Videos: Quality and Permission Together','quality and creator permission'],['tiktok-downloader-hd-resolution-and-mp4-guide','TikTok Resolution and MP4: What to Check','resolution and MP4 playback'],['tiktok-video-downloader-hd-best-quality-guide','TikTok Quality: Test Captions and Motion','captions and motion'],['tiktok-downloader-video-mobile-and-desktop-guide','TikTok Files on Mobile and Desktop','moving a permitted file between devices'],['tiktokvideo-downloader-search-intent-guide','TikTok Video Links: Use the Correct Source','the individual video source'],['tiktok-to-mp4-download-format-guide','TikTok to MP4: Preserve Portrait Framing','portrait MP4 framing'],['download-audio-from-tiktok-mp3-and-m4a-guide','TikTok Audio: Check Speech and Music Quality','audio quality and file choice'],['tiktok-downloader-hd-resolution-and-mp4-guide','TikTok Resolution: A Practical File Check','a practical resolution check']
  ];$slugs=array_column($items,0);$slugs=array_values(array_unique($slugs));if(count($slugs)!==9){$items[]=['tiktok-without-watermark-responsible-saving-guide','TikTok Clean Copies: Keep Attribution Clear','creator attribution'];$slugs=array_column($items,0);$slugs=array_values(array_unique($slugs));} $rows=DB::table('blog_posts')->whereIn('slug',$slugs)->lockForUpdate()->get();if($rows->count()!==count($slugs))throw new \RuntimeException('Target articles missing; stopped safely.');DB::transaction(function()use($items,$rows){$backup=dirname(base_path()).'/tiktok-batch-ten-'.date('Ymd-His').'.json';file_put_contents($backup,json_encode($rows,JSON_PRETTY_PRINT),LOCK_EX);chmod($backup,0600);$seen=[];foreach($items as [$slug,$title,$focus]){if(isset($seen[$slug]))continue;$seen[$slug]=1;$content='<p>This guide focuses on '.$focus.' so you can make a clear choice without repeating a keyword. Use your own, licensed, public-domain, or explicitly permitted TikTok material.</p><h2>Check the individual video</h2><p>Open the exact post, confirm the creator and title, and copy the video URL rather than a profile or search page. Public playback does not automatically authorize editing or reposting.</p><h2>Test the result</h2><ol><li>Play the beginning and ending.</li><li>Check speech, music, and sync.</li><li>Inspect captions and portrait edges.</li><li>Open the file on the destination device.</li></ol><p>If the result is missing, check Downloads as well as Photos or Gallery. If it becomes blurry only after sharing, the destination app compressed it.</p><h2>Keep context and account safety</h2><p>Save the creator name, source URL, date, and permission note with the file. Never provide a TikTok password, browser cookie, or payment detail to an unknown tool.</p><p>Use the <a href="/tiktok-video-downloader">TikTok platform guide</a> and the <a href="/supported-platforms">supported platforms directory</a> for related sources.</p>';$data=['title'=>$title,'excerpt'=>'A practical guide to '.$focus.'.','meta_title'=>$title,'meta_description'=>'A practical guide to '.$focus.'.','content'=>$content,'read_minutes'=>1,'updated_at'=>now()];DB::table('blog_posts')->where('slug',$slug)->update($data);}$this->command->info('Updated '.count($seen).' articles. Backup: '.$backup);});
 }
}
