<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RewriteFinalTemplateBatchSeeder extends Seeder
{
 public function run(){
  $items=[
   ['instagram-video-downloader-public-video-guide','Instagram Public Videos: Verify the Post Before Saving','Instagram public video posts','instagram-video-downloader'],['x-video-downloader-public-post-video-guide','X Videos: Keep the Post URL and Creator Context','X public video posts','twitter-video-downloader'],['twitter-to-mp3-audio-saving-guide','X Audio: Check the Source Before Extracting Sound','X audio files','twitter-video-downloader'],['pinterest-video-downloader-hd-public-pin-guide','Pinterest HD Pins: Check the Original Detail','Pinterest HD video Pins','pinterest-video-downloader'],['pinterest-video-downloader-free-safe-online-guide','Pinterest Public Pins: Browser Safety Checklist','safe Pinterest browser use','pinterest-video-downloader'],['story-downloader-for-snapchat-what-to-know','Snapchat Stories: Understand Availability and Permission','Snapchat Story availability','snapchat-video-downloader'],['video-downloader-complete-online-saving-guide','Online Video Files: Choose a Safe Saving Workflow','online video saving','supported-platforms'],['online-video-downloader-public-url-guide','Online Video Links: Check the Exact Public URL','public video URLs','supported-platforms'],['4k-video-downloader-quality-and-file-size-guide','4K Video: Balance Detail, Device Support, and Storage','4K quality and storage','supported-platforms'],['mp4-video-downloader-compatibility-guide','MP4 Video Files: Check Codec and Audio','MP4 compatibility','supported-platforms'],['video-downloader-mp4-best-format-guide','Video MP4: Pick a Format for the Destination Device','MP4 format selection','supported-platforms'],['pinterest-solution-hub-quality-tips','Pinterest Video Quality: A Useful Pin Checklist','Pinterest video quality','pinterest-video-downloader']
  ];$slugs=array_column($items,0);$rows=DB::table('blog_posts')->whereIn('slug',$slugs)->lockForUpdate()->get();if($rows->count()!==count($items))throw new \RuntimeException('Target articles missing; stopped safely.');DB::transaction(function()use($items,$rows){$backup=dirname(base_path()).'/final-template-batch-'.date('Ymd-His').'.json';file_put_contents($backup,json_encode($rows,JSON_PRETTY_PRINT),LOCK_EX);chmod($backup,0600);foreach($items as [$slug,$title,$focus,$route]){$content='<p>This guide focuses on '.$focus.' and gives one clear workflow for a real visitor. Use only your own, licensed, public-domain, or explicitly permitted media.</p><h2>Start with the exact source</h2><p>Open the individual post, Pin, Story, or video and confirm the creator, title, and current availability. Copy the individual URL rather than a profile or search page. A public player does not automatically give permission to edit or repost the work.</p><h2>Check the result on your device</h2><ol><li>Play the opening, middle, and ending.</li><li>Check sound and synchronization.</li><li>Inspect captions, fine detail, and orientation.</li><li>Confirm duration and file size.</li><li>Open the copy on the device where it will be used.</li></ol><p>If the file is not visible, check the browser Downloads folder as well as Photos or Gallery. If it becomes blurry only after sharing, the destination app compressed it.</p><h2>Keep the context</h2><p>Use a descriptive filename and store the source URL, creator name, date, and permission note beside it. Do not share passwords, cookies, or payment details with an unknown tool.</p><p>Continue with the <a href="/'.$route.'">relevant platform guide</a> and browse <a href="/supported-platforms">supported platforms</a> for related sources.</p>';$data=['title'=>$title,'excerpt'=>'A practical guide to '.$focus.'.','meta_title'=>$title,'meta_description'=>'A practical guide to '.$focus.'.','content'=>$content,'read_minutes'=>1,'updated_at'=>now()];DB::table('blog_posts')->where('slug',$slug)->update($data);}$this->command->info('Updated '.count($items).' final template articles. Backup: '.$backup);});
 }
}
