<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RewriteYoutubeBatchNineSeeder extends Seeder
{
 public function run(){
  $items=[
   ['download-video-youtube-hd-quality-explained','YouTube HD: Compare Detail at Normal Viewing Size','comparing HD detail'],['download-yt-video-mobile-and-desktop-guide','YouTube Files on Mobile and Desktop','moving an authorized file between devices'],['download-youtube-clips-responsible-saving-guide','YouTube Clips: Keep the Source and Creator Context','organizing short clips'],['free-online-youtube-video-download-guide','YouTube Online Tools: Check the Workflow Before Use','checking browser tools safely'],['free-youtube-video-downloader-for-android-safer-options','YouTube on Android: Storage and Playback Checks','Android storage and playback'],['youtube-to-mp3-converter-audio-quality-and-safety','YouTube Audio: Choose a Clear, Permission-Based Export','audio export quality'],['youtube-to-mp3-common-mistakes-to-avoid','YouTube Audio Conversion: Mistakes That Reduce Quality','avoiding repeated conversion'],['youtube-downloader-audio-video-format-comparison','YouTube Audio or Video: Choose the Right Result','choosing audio versus video'],['youtube-audio-downloader-4k-what-the-keyword-really-means','YouTube Audio and “4K”: Understand the Label','understanding misleading audio labels'],['youtube-to-mp4-download-reddit-questions-answered','YouTube MP4 Questions: Check the File, Not the Rumor','answering common MP4 questions']
  ];$slugs=array_column($items,0);$rows=DB::table('blog_posts')->whereIn('slug',$slugs)->lockForUpdate()->get();if($rows->count()!==10)throw new \RuntimeException('Target articles missing; stopped safely.');DB::transaction(function()use($items,$rows){$backup=dirname(base_path()).'/youtube-batch-nine-'.date('Ymd-His').'.json';file_put_contents($backup,json_encode($rows,JSON_PRETTY_PRINT),LOCK_EX);chmod($backup,0600);foreach($items as [$slug,$title,$focus]){$content='<p>This guide focuses on '.$focus.' and explains the decision in plain language. Use only your own, licensed, public-domain, or explicitly permitted material.</p><h2>Begin with the exact source</h2><p>Open the individual YouTube video, confirm its title and creator, and copy the video URL rather than a channel or search page. A public video can still have restrictions on copying, editing, or redistribution.</p><h2>Make a small test first</h2><ol><li>Check the opening and ending.</li><li>Listen for complete and synchronized audio.</li><li>Inspect captions or small detail.</li><li>Confirm duration, orientation, and file size.</li></ol><p>Open the result on the device where it will be used. If it is missing, check the browser Downloads folder as well as Photos or Gallery. Keep the original working copy before making a smaller export.</p><h2>Keep the context</h2><p>Use a descriptive filename and store the source URL, creator name, and permission note beside it. Do not share passwords, cookies, or payment details with an unknown tool.</p><p>Use the <a href="/youtube-video-downloader">YouTube platform guide</a> for public-link checks and the <a href="/supported-platforms">supported platforms directory</a> for other services.</p>';$data=['title'=>$title,'excerpt'=>'A practical guide to '.$focus.'.','meta_title'=>$title,'meta_description'=>'A practical guide to '.$focus.'.','content'=>$content,'read_minutes'=>1,'updated_at'=>now()];DB::table('blog_posts')->where('slug',$slug)->update($data);}$this->command->info('Updated 10 articles. Backup: '.$backup);});
 }
}
